# Generated by Django 4.0.1 on 2022-04-12 18:11

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User', models.CharField(max_length=20, verbose_name='Автор')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='Название!')),
                ('description', models.TextField(max_length=180, verbose_name='Описание')),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(0, 'Quantity should be >= 0')], verbose_name='Количество')),
                ('price', models.FloatField(default=0.0, verbose_name='Цена')),
                ('date_pub', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('category', models.ForeignKey(blank=True, max_length=15, null=True, on_delete=django.db.models.deletion.CASCADE, to='simpleapp.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Разновидность',
                'verbose_name_plural': 'Разновидности',
            },
        ),
    ]
